### PR TITLE
Producers memory bloat / connections leak

### PR DESCRIPTION
**Pull request by soid**
If you wanna send thousand messages using KafkaUnit.sendMessages() you'll run into connections leak.
This fix creates the producer lazily.

### CODE REVIEW

**Comment by soid** [comment]
Whoops, I wanted to create a different pull request for the second change, but don't see how to do it. Let me know if you want a separate PR for it, I'll figure it out.

I just needed to customize the log.segment.bytes parameter, but I thought it might be useful to customize other parameters as well.
Not really sure about exposing the KafkaServerStartable memeber. I did it just for the test, but I felt it might be useful for some other tests too. Please let me know if you think it might be a problem or if you want an accessor method for it.

**Comment by chbatey** [comment]
thanks for the PR, I'll take a look at this soon

**Comment by soid** [comment]
FYI this PR blocks the kafka HDFS driver "Kangaroo" PR for kafka 0.8 compatibility: https://github.com/Conductor/kangaroo/pull/7

No rush, but it would be good to release them soon. Let me know if I can help with reviewing it.

Thank you!

**Comment by soid** [comment]
Thanks for merging it, Christopher! Can you please push the maven artifact as well?

**Comment by chbatey** [comment]
Doing a release now

**Comment by chbatey** [comment]
Thanks for the contribution @soid should be synced to maven central within 30 minutes.

**Pull request merged**
