### PR TITLE
Feature/bump kafka version

### PR DESCRIPTION
**Pull request by Qnzvna**
bumping kafka version to kafka_2.11:0.11.0.0, zookeeper to 3.4.10, using `ProducerRecord` instead of depreacated `KeyedMessage`

### CODE REVIEW

**Comment by Qnzvna** [comment]
@chbatey Could you review this PR, I've removed deprecated API and upgraded kafka to the newest version.
That PR will close #60 and #43

**Comment by Qnzvna** [comment]
Could we merge this as new version of kafka should be supported.

**Comment by chbatey** [comment]
Looks good :+1:

**Comment by Qnzvna** [comment]
When are you planning to do the release of 1.0?

**Pull request merged**
