### PR TITLE
Updated to Kafka client 0.10.1.0 and bumped version to 0.7.

### PR DESCRIPTION
**Pull request by vbence**
Tracking the latest client version.

### CODE REVIEW

**Comment by DieBauer** [comment]
As of Kafka 0.10 the keyedmessage is deprecated in favor of the ProducerRecord.

Could you take that into account?

**Comment by vbence** [comment]
I will look into it.

**Comment by vbence** [comment]
Kept the deprecated stuff on outward-facing APIs (just deprecated those methods), added alternative methods with new APIs. (Deprecated stuff can be removed on a later date ofc.)

**Comment by vbence** [comment]
Superseded by #43 .

**Pull request closed without merging**
